// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Volo.Abp.Domain.Entities;

namespace AdminSSO.AuthApps
{
    public partial class AuthApp: Entity<int>
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public bool? IsActived { get; set; }
        public bool? IsDeleted { get; set; }
    }
}