// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Volo.Abp.Domain.Entities;

namespace AdminSSO.RoleMapUsers
{
    public partial class RoleMapUser:Entity<int>
    {
       
        public int? UserId { get; set; }
        public int? RoleId { get; set; }
        public int? Type { get; set; }
        public bool? IsDeleted { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public string CreatedBy { get; set; }
    }
}