// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Volo.Abp.Domain.Entities;

namespace AdminSSO.Roles
{
    public partial class Role : Entity<int>
    {
        public string Name { get; set; }
        public string RoleCode { get; set; }
        public string Description { get; set; }
        public bool? IsActived { get; set; }
        public bool? IsDeleted { get; set; }
        public DateTime? DateCreated { get; set; }
        public string CreatedBy { get; set; }
    }
}